# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift

use_frameworks!

target ‘WeatherApp’ do

#pod 'MMParallaxCell', '~> 1.2'

pod 'Alamofire'
pod 'SVProgressHUD'
pod 'TPKeyboardAvoiding'
pod 'KeyboardDismisser'
pod 'ScrollTo'
pod 'ActionSheetPicker-3.0'
pod 'TTTAttributedLabel', '~> 2.0'

pod 'SwipeView', '~> 1.3'

pod 'AlamofireImage', '~> 3.3'

pod 'Bagel', :git => 'https://github.com/yagiz/Bagel.git', :branch => 'pre'

end
